---
# 1. Common + user op alle nodes
- name: Basisrollen toepassen op alle nodes
  hosts: ubuntu_nodes
  become: true

  roles:
    - common
    - role: user
      vars:
        add_sudo: true
        add_ssh_key: true

# 2. Alleen nginx op hosts in groep [nginx]
- name: Installeer nginx op nginx-hosts
  hosts: nginx
  become: true

  roles:
    - apps/nginx

# 3. Installatie postgres op host in groep [postgres]
- name: Installeer PostgreSQL op postgres-nodes
  hosts: postgres
  become: true

  roles:
    - apps/postgres

# 4. Installatie file op host in de groep [files]
- name: Test zip deploy
  hosts: files
  become: true
  roles:
    - deploy_zip

