collections:
  - name: community.general
    version: ">=7.0.0"
  - name: community.docker
    version: ">=3.10.0"
  - name: ansible.posix
  - name: oracle.oci
    version: 5.5.0
    source: https://galaxy.ansible.com

roles:
  - name: ubuntu20-cis
    src: https://github.com/ansible-lockdown/UBUNTU20-CIS
    version: main

