---
- name: Zorg dat vereiste pakketten aanwezig zijn
  apt:
    name:
      - unzip
      - libaio1
      - wget
    state: present
  become: true

- name: Maak installatiepad aan
  file:
    path: /opt/oracle
    state: directory
    mode: '0755'
  become: true

- name: Download Oracle Instant Client BasicLite
  get_url:
    url: "{{ oracle_client_url_basic }}"
    dest: /opt/oracle/oracle-instantclient-basic.zip
  become: true

- name: Download Oracle Instant Client SQLPlus
  get_url:
    url: "{{ oracle_client_url_sqlplus }}"
    dest: /opt/oracle/oracle-instantclient-sqlplus.zip
  become: true

- name: Pak beide archives uit
  unarchive:
    src: "{{ item }}"
    dest: /opt/oracle/
    remote_src: true
  with_items:
    - /opt/oracle/oracle-instantclient-basic.zip
    - /opt/oracle/oracle-instantclient-sqlplus.zip
  become: true

- name: Maak symlink voor sqlplus
  file:
    src: /opt/oracle/instantclient_{{ oracle_client_version }}/sqlplus
    dest: /usr/bin/sqlplus
    state: link
  become: true

- name: Zet environment-variabelen in /etc/profile.d/oracle_client.sh
  copy:
    dest: /etc/profile.d/oracle_client.sh
    content: |
      export ORACLE_HOME=/opt/oracle/instantclient_{{ oracle_client_version }}
      export LD_LIBRARY_PATH=$ORACLE_HOME
      export PATH=$PATH:$ORACLE_HOME
    mode: '0755'
  become: true

- name: Plaats tnsnames.ora
  template:
    src: tnsnames.ora.j2
    dest: /opt/oracle/instantclient_{{ oracle_client_version }}/network/admin/tnsnames.ora
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Plaats sqlnet.ora
  template:
    src: sqlnet.ora.j2
    dest: /opt/oracle/instantclient_{{ oracle_client_version }}/network/admin/sqlnet.ora
    owner: root
    group: root
    mode: '0644'
  become: true

# ===============================
# 🔹 Test TCPS connectie + validatie
# ===============================
- name: Test TCPS connectie met sqlplus (via Credential env vars, non-interactive)
  shell: |
    echo "exit" | sqlplus -s {{ ORACLE_USERNAME }}/{{ ORACLE_PASSWORD }}@LUIZ
  environment:
    ORACLE_HOME: "/opt/oracle/instantclient_{{ oracle_client_version }}"
    PATH: "/opt/oracle/instantclient_{{ oracle_client_version }}:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "/opt/oracle/instantclient_{{ oracle_client_version }}"
    TNS_ADMIN: "/opt/oracle/instantclient_{{ oracle_client_version }}/network/admin"
  register: sqlplus_test
  timeout: 20
  ignore_errors: true
  become: true

- name: Toon resultaat van TCPS connectie
  debug:
    var: sqlplus_test.stdout

- name: Controleer op ORA-fouten in sqlplus output
  fail:
    msg: "❌ SQL*Plus connectie mislukt: {{ sqlplus_test.stdout | trim }}"
  when:
    - sqlplus_test.stdout is defined
    - sqlplus_test.stdout is search("ORA-")

- name: Bevestig succesvolle TCPS-verbinding
  debug:
    msg: "✅ Oracle Client heeft succesvol verbinding gemaakt met {{ ORACLE_USERNAME }}@LUIZ"
  when: sqlplus_test.stdout is search("Connected to:")

# ===============================
# 🔹 Controleer clientversie
# ===============================
- name: Verifieer installatie
  shell: ". /etc/profile.d/oracle_client.sh && sqlplus -V"
  register: sqlplus_version
  changed_when: false

- name: Toon Oracle Client versie
  debug:
    msg: "{{ sqlplus_version.stdout }}"

