---

- name: Installeer PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes

- name: Start PostgreSQL handmatig (Docker workaround)
  shell: "pg_ctlcluster 12 main start"
  become: true
  args:
    executable: /bin/bash
  register: pgstart
  failed_when: >
    pgstart.rc != 0 and
    ('already running' not in pgstart.stdout | lower)

- name: Maak testdatabase aan (sudo -u postgres)
  shell: |
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='demo_db'" \
      || sudo -u postgres psql -c "CREATE DATABASE demo_db;"
  become: true          # blijf root in de container
  args:
    executable: /bin/bash

- name: Voeg PostgreSQL gebruiker toe (sudo -u)
  shell: |
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='appuser'" \
      || sudo -u postgres psql -c "CREATE USER appuser WITH PASSWORD 'securepass';"
  become: true
  args:
    executable: /bin/bash

- name: Maak database aan voor appuser (sudo -u)
  shell: |
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='appdb'" \
      || sudo -u postgres psql -c "CREATE DATABASE appdb OWNER appuser;"
  become: true                # blijf root in container
  args:
    executable: /bin/bash
    
# tasks file for roles/postgres
