- name: Install dependencies for btop
  become: true
  ansible.builtin.apt:
    name:
      - wget
      - gnupg
    state: present
    update_cache: true

- name: Download btop .deb package
  ansible.builtin.get_url:
    url: https://github.com/aristocratos/btop/releases/latest/download/btop-x86_64-linux.deb
    dest: /tmp/btop.deb
    mode: '0644'

- name: Install btop using dpkg
  become: true
  ansible.builtin.apt:
    deb: /tmp/btop.deb

