---
- name: Install snapd (if needed)
  ansible.builtin.apt:
    name: snapd
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Enable snapd socket
  ansible.builtin.systemd:
    name: snapd.socket
    enabled: true
    state: started
  become: true
  when: ansible_os_family == "Debian"

- name: Install btop via snap
  become: true
  community.general.snap:
    name: btop
    classic: true
  when: ansible_os_family == "Debian"

