---
- name: Install btop via snap
  become: true
  community.general.snap:
    name: btop
    classic: true
  when: ansible_os_family == "Debian"

- name: Install btop via dnf
  ansible.builtin.dnf:
    name: btop
    state: present
  when: ansible_os_family == "RedHat"
