---
- name: Maak nieuwe Ubuntu container AWX-ready
  hosts: dockerhost
  become: true
  gather_facts: false

  vars:
    container_name: "{{ container_name | default('ubuntu06') }}"
    container_image: "{{ container_image | default('ubuntu:20.04') }}"
    container_port: "{{ container_port | default(2226) }}"
    ssh_public_key: "{{ lookup('file', '/runner/.ssh/id_rsa.pub') }}"

  tasks:

    - name: Controleer of Docker aanwezig is
      ansible.builtin.command: which docker
      register: docker_check
      failed_when: docker_check.rc != 0
      changed_when: false

    - name: Maak container aan
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        state: started
        restart_policy: unless-stopped
        tty: true
        detach: true
        ports:
          - "{{ container_port }}:22"
        command: /usr/sbin/sshd -D
      register: container_info

    - name: Installeer openssh-server in container
      community.docker.docker_exec:
        container: "{{ container_name }}"
        command: |
          bash -c "apt-get update && apt-get install -y openssh-server sudo vim"

    - name: Voeg 'ansible' user toe
      community.docker.docker_exec:
        container: "{{ container_name }}"
        command: |
          bash -c "useradd -m -s /bin/bash ansible && echo 'ansible:ansible' | chpasswd && usermod -aG sudo ansible"

    - name: Maak .ssh map aan
      community.docker.docker_exec:
        container: "{{ container_name }}"
        command: bash -c "mkdir -p /home/ansible/.ssh && chmod 700 /home/ansible/.ssh && chown -R ansible:ansible /home/ansible/.ssh"

    - name: Voeg AWX-public key toe aan authorized_keys
      community.docker.docker_exec:
        container: "{{ container_name }}"
        command: |
          bash -c "echo '{{ ssh_public_key }}' >> /home/ansible/.ssh/authorized_keys && chmod 600 /home/ansible/.ssh/authorized_keys && chown ansible:ansible /home/ansible/.ssh/authorized_keys"

    - name: Controleer of SSH-server draait
      community.docker.docker_exec:
        container: "{{ container_name }}"
        command: bash -c "service ssh start || systemctl start ssh"

    - name: Toon container info
      ansible.builtin.debug:
        msg: |
          ✅ Nieuwe container aangemaakt:
          Naam: {{ container_name }}
          Image: {{ container_image }}
          SSH-poort: {{ container_port }}

