---
- name: Voer Goss CIS audit uit op containers
  hosts: ubuntu_nodes
  become: true
  vars:
    audit_dest: /opt/20-CIS-Audit

  tasks:
    - name: Maak auditfolder aan op remote host
      file:
        path: "{{ audit_dest }}"
        state: directory
        mode: '0755'

    - name: Kopieer volledige auditstructuur (recursief)
      copy:
        src: /home/stefan/mijn_ansible1/files/UBUNTU20-CIS-Audit/
        dest: "{{ audit_dest }}/"
        mode: '0755'
        owner: root
        group: root
        remote_src: no

    - name: Installeer Goss (indien nodig)
      shell: |
        if ! command -v goss >/dev/null; then
          curl -fsSL https://goss.rocks/install | sh
        fi
      args:
        executable: /bin/bash

    - name: Draai audit zonder systemd checks
      shell: |
        chmod +x {{ audit_dest }}/run_audit.sh
        GOSS_FILES_STRATEGY=deep \
        GOSS_SKIP='systemd' \
        {{ audit_dest }}/run_audit.sh \
          -f json \
          -v {{ audit_dest }}/vars/CIS.yml \
          -o {{ audit_dest }}/audit_output.json
      args:
        executable: /bin/bash
        chdir: "{{ audit_dest }}"

    - name: Haal audit-resultaat op
      fetch:
        src: "{{ audit_dest }}/audit_output.json"
        dest: "/home/stefan/mijn_ansible1/results/{{ inventory_hostname }}.json"
        flat: yes

